### ISSUE TITLE
OBS web application crashes with http response code 500 internal server error

### ISSUE THREAD

**Issue by reSHARMA** [opencollab/llvm-slave-salt#6]

**Comment by reSHARMA** [comment]
Output from `/var/log/obs/production.log` 
```
[757a619c-43f3-48f6-8a89-10fceb88863f] [15650:4868.55] Started GET "/" for 127.0.0.1 at 2018-05-24 11:19:52 +0200
[757a619c-43f3-48f6-8a89-10fceb88863f] [15650:4868.55] Processing by Webui::MainController#index as HTML
[757a619c-43f3-48f6-8a89-10fceb88863f] [15650:4871.61] Completed 500 Internal Server Error in 3054ms (ActiveRecord: 2.4ms | Backend: 0.0ms | XML: 0.0ms)
[757a619c-43f3-48f6-8a89-10fceb88863f] [15650:4871.61] 
ActiveXML::Transport::Error (<status code="400">
  <summary>connect to irill8.inria.fr:5252: No route to host</summary>
</status>
):
```
In reference to https://openbuildservice.org/help/manuals/obs-admin-guide/obs.cha.overview_filesystem.html#idm140378288254768 I've checked all the places for source and repo server to be 'localhost' and I'm able to access http://localhost:5252 http://localhost:5152 through ssh tunneling.

Some where internally hostname is directly used instead of the one set in configuration else  irill8.inria.fr:5252 won't be possible

Content of `/usr/share/obs/overview/index.html`
```
<p>
<a href="https://irill8.siege.inria.fr">The OBS web interface</a> can be used to setup OBS, browse the content and to build packages. It is also the api url to be used with clients like osc.
</p>

<p>
<a href="http://irill8.siege.inria.fr:82">The OBS repositories</a> contain the build results, the repositories can be added to package managers like zypper or apt.
</p>

<p>
The Open Build Service project can be found at <a href="http://www.openbuildservice.org">www.openbuildservice.org</a>. And the openSUSE project is hosting a public instance of OBS at <a href="http://build.opensuse.org">build.opensuse.org</a> which is not limited to SUSE distributions.
</p>

```
This file is generated even before the configuration and at the time of installation of obs-api and remain unaffected even when new configuration are made and is available on http://localhost:80 I could just find  `/usr/lib/obs/server/setup-appliance.sh`  which generate this

```
function create_overview_html {
  echo "Creating overview.html"
  sed -e "s,___API_URL___,https://$FQHOSTNAME,g" \
      -e "s,___REPO_URL___,http://$FQHOSTNAME:82,g" \
      /srv/www/obs/overview/overview.html.TEMPLATE > /srv/www/obs/overview/index.html
}
```
This did not run as it is not for debian, and I could not find a equivalent one which would have run at the time of installation.

If somehow it starts to call localhost:5252 OBS will stop crashing, but the output from korcula when obsworker is started.

```
Run 8 obsworker using /srv/obs/worker
Type of obsworker is chroot
Fetching initial worker code from http://irill8.siege.inria.fr:5252
```
As it is not able to reach http://irill8.siege.inria.fr:5252 it stops.
Though when I tried to keep obsworker on irill8 OBS was still crashing so primarily we should fix irill.

**Comment by sylvestre** [comment]
I asked for the ports to be opened.

**Comment by athos-ribeiro** [comment]
Just to register here that the schedulers were pointing to __irill8.inria.fr__ instead of __irill8.siege.inria.fr__`. I am trying to replicate the issue to understand why. After that, we can close this issue.

This is not an issue in our instance anymore. Is the server being constatly provisioned with the salt code in this repository?

**Comment by sylvestre** [comment]
Not using obs
